### ISSUE TITLE
pnpm 8.0 support

### ISSUE THREAD

**Issue by chrisbbreuer** [pkgxdev/pantry#1027]
I was just trying to give pnpm 8 a shot on tea v0.26.0 and the error I am receiving is:

> we haven’t packaged pnpm.io^8. but we will…

While it is a brand-new release, it seems it needs to be updated here still: https://dist.tea.xyz/?prefix=pnpm.io/

I am curious to find out how an update is triggered there 🙂

**Comment by jhheider** [comment]
Triggered a build; we've just yesterday updated our release-finding logic to use active scanning of GitHub, rather than passive notification of releases, so we should have much better new version coverage. Not every project uses releases, some just use tags, and now our monitoring logic should cleave tightly to `cli`'s logic.

**Comment by jhheider** [comment]
https://github.com/teaxyz/pantry/actions/runs/4558295455

**Comment by chrisbbreuer** [comment]
Thanks for resolving this & for the explanation ❤️

**Comment by jhheider** [comment]
Community thrives on transparency. ;)
