### ISSUE TITLE
Package description doesn't match package

### ISSUE THREAD

**Issue by philippgille** [pkgxdev/pantry#1463]
Hello :wave: , thanks for your efforts on this open source project :muscle: 

I looked a bit around the available packages, and noticed that <https://tea.xyz/+google.com/glog/> says "Unofficial downloader for GOG.com games"

Screenshot: 
![image](https://user-images.githubusercontent.com/170670/232315839-f0260ae1-615f-4e18-b9c4-8eb3494c7268.png)

But the package is for Google's `glog`, their C++ implementation for the glog logger, unrelated to GOG or games.

- Package: <https://github.com/teaxyz/pantry/blob/3e7758875003556398ec2f691ec7c989563d30f3/projects/google.com/glog/package.yml>
- Google's glog: <https://github.com/google/glog>

Then I tried to find the place where this can be fixed, but the package YAML doesn't contain the description. Searching GitHub for "Unofficial downloader" across the teaxyz organization didn't find this string either.

=> This ticket is twofold:

1. Fix the description of glog
2. Document or improve the system that sets the descriptions, for example by having it in the package YAML, or by having a pantry website-specific YAML next to the package YAML in <https://github.com/teaxyz/pantry/tree/e2e2e4160e6379ce0d5de0d818385cfd4a8e4ca7/projects/google.com/glog>

**Comment by mxcl** [comment]
I fixed this in 10 seconds. Well done @getneil on taking 5 days to do nothing.

We have plans to expose the descriptions to the community in the long term, as yet we do not because @getneil decided to work alone on this feature without consulting anyone and now it is stored in a properietary database rather than in a form that works for an open source project.

I'm very unimpresed.
