### ISSUE TITLE
make `pkg build` reentrant 

### ISSUE THREAD

**Issue by aslafy-z** [pkgxdev/pantry#3581]
When working on package build, I noticed that a `pkg build` done over a previous failed build attempt fails with

```
error: Uncaught AlreadyExists: File exists (os error 17): symlink '/home/zadkiel/.pkgx/llvm.org/v*/bin/clang' -> '/home/zadkiel/work/pkgx-pantry/builds/argoproj.github.io∕workflows-3.4.11+linux/dev.pkgx.bin/cc'
    Deno.symlinkSync(target.string, this.string)
         ^
    at Object.symlinkSync (ext:deno_fs/30_fs.js:490:7)
    at Path.ln (https://deno.land/x/libpkgx@v0.14.1/src/utils/Path.ts:324:10)
    at symlink (file:///home/zadkiel/.pkgx/pkgx.sh/brewkit/v0.49.0/libexec/stage.ts:72:14)
    at file:///home/zadkiel/.pkgx/pkgx.sh/brewkit/v0.49.0/libexec/stage.ts:76:5
    at eventLoopTick (ext:core/01_core.js:183:11)
```

I found that `rm -r builds` makes it work, but it's pretty annoying.

**Comment by mxcl** [comment]
builds deliberately don't clean first since it makes debugging harder. If you want to clean first do `pkg clean && pkg build`.

this particular issue is specific to the llvm package and can be fixed there. Forcing the symlink would be enough though I feel this isn't right since we do want this failure should llvm decide to create their own symlinks as part of the build process, so a more thorough check would be required which is a lot of work just to fix reentrant builds for a single package considering usually the build just works.

**Comment by mxcl** [comment]
we provide `bk build --clean` now
