### ISSUE TITLE
nodejs.org can't be injected into the local environment

### ISSUE THREAD

**Issue by sanchitram1** [pkgxdev/pantry#4104]
.pkgx.yaml

```yaml
dependencies:
  python@3.11 pip.pypa.io xc node ruff psql
```

command I try

```
$ dev
× unexpected error cannot intersect: ^71 && ^73
│ Error: cannot intersect: ^71 && ^73
│     at Module.intersect (https://deno.land/x/libpkgx@v0.15.0/src/utils/semver.ts:382:30)
│     at hydrate (https://deno.land/x/libpkgx@v0.15.0/src/plumbing/hydrate.ts:51:48)
│     at eventLoopTick (ext:core/01_core.js:183:11)
│     at async failsafe (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/failsafe.ts:5:12)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/prefab/install.ts:10:41)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/modes/internal.activate.ts:26:25)
│     at async default (file:///Users/builder/actions-runner/_work/pkgx/pkgx/src/app.ts:77:35)
│     at async file:///Users/builder/actions-runner/_work/pkgx/pkgx/entrypoint.ts:59:3
╰─➤ https://github.com/pkgxdev/pkgx/issues/new
```

through process of elimination, i've identified that node is the one throwing me the error.  I can paste all the packages in my .pkgx/.local here if that helps.

**Comment by jhheider** [comment]
this is a thorny issue. it boils down like this:
- compiling against one major of unicode locks a build to that version
- if it depends on unicode.org: '*', then it won't work at all with a different version
- postgres is locked to ^73, almost all our other projects are locked to ^71
- probably the answer is to allow multiple versions of things (some, all?), but that's complicated.

@mxcl an example of unicode versioning being a problem. One option might be to have fix-machos.rb use `v*` if that was the dep specified, but that has other risks.

**Comment by sanchitram1** [comment]
aren't dependencies semver'd?  so if node depends on ^71, pkgx would ensure that it uses unicode^71, while postgres uses unicode^73?

or are you saying that my .pkgx/.local can only have one version of unicode injected?

**Comment by jhheider** [comment]
Your dev environment can only have one version of Unicode loaded. The only trick you might employ right now is to use `pkgx psql` or `pkgx install postgresql.com` *instead* of adding it to your env.

**Comment by mxcl** [comment]
Probs we should stop adding transitive libraries to the env part of the devenv. Though this will screw windows. So maybe not.

What I mean is: mac and linux have rpath systems that allow the library information to be kept out of the “env”, each tool knows how to find the libs it needs individually so the overall env can ignore that info. The only time we would then surface libraries to the env itself is non-transitive (ie. explicitly added) deps.

That would fix this and a lot of other potential stuff in the future.

For now the fix is removing all `unicode.org: *` deps and constraining everything to v71 like we did for python 3.11

**Comment by mxcl** [comment]
In future all '*' deps must be rejected.

**Comment by mxcl** [comment]
`pkgx` is the first package manager that can support eg. `unicode^71 && uniscode^73`, it is then up to the tool that needs unicode to find the version it wants† or in terms of runtime linkage, up to the platform to have robust systems for finding the correct dylib (mac/linux use rpath, windows uses well named DLLs eg `unicode73.dll`).

So we *could* add everything twice to the environment.

Dropping transitive deps will break in subtle ways without shims for everything‡, eg. if git depends on libxml it may actually need `xml-config` in `PATH` for some reason. Notably I think the breakage for transitive deps is only likely if we drop `PATH`. But whichever env vars we choose are necessary we still have the above conflict issue to solve.

Either way we need a solution since currently:

```sh
pkgx +python@3.11 +pip +xc +node +ruff +psql sh
```

Is an easy way to demonstrate the issue. I don’t believe we are in a position where we can standardize on a single version of unicode.

Perhaps a simple temporary fix is to allow conflicts for hard coded deps like libunicode.

> † this will not be “just works TM” for many things tho sadly
> ‡ and possibly shims for everything is the correct solution for `dev`envs TBH
