### ISSUE TITLE
version request: ktlint.github.io@0.49.0

### ISSUE THREAD

**Issue by jakobvase** [pkgxdev/pantry#4982]
I need this for a project. I'll see if I can add it myself

**Comment by mxcl** [comment]
https://github.com/pkgxdev/pantry/actions/runs/7653751203

**Comment by mxcl** [comment]
They changed the filename format of their tarballs in between versions. Typical “open source” from a web2 shop (they don’t care about the details that matter to the community, just about showing off their open source chops).

brewkit doesn't have a way to vary filenames yet since it only happens when crappy web2 devshops don’t know what they are doing. Possibly we can use the standard github urls? I don’t know the package.

https://github.com/pinterest/ktlint/archive/refs/tags/0.49.0.zip

**Comment by jakobvase** [comment]
Hmm ok. I had a look and it looks like the correct link for both versions is https://github.com/pinterest/ktlint/releases/download/{{version}}/ktlint

**Comment by jakobvase** [comment]
But that doesn't download a zip, but a shell script that includes a jar. It's the same file that's normally inside the zip. Can we download it unzipped?

**Comment by jakobvase** [comment]
They only started including zipped versions from 0.50.0

**Comment by jakobvase** [comment]
Or actually 0.49.1

**Comment by jakobvase** [comment]
So if you trigger 0.49.1, it should work

**Comment by jhheider** [comment]
0.49.1: https://github.com/pkgxdev/pantry/actions/runs/7656558860

**Comment by jakobvase** [comment]
0.49.1 works for me, and the earlier versions are complicated (see https://github.com/pkgxdev/pantry/pull/4983). Thanks!
