### ISSUE TITLE
`pkgx deno compile --target aarch64-apple-darwin main.ts` on linux always generate executable for linux

### ISSUE THREAD

**Issue by tsirysndr** [pkgxdev/pantry#6790]
`pkgx deno compile -A --output main --target aarch64-apple-darwin  main.ts` on linux always generate executable for linux.

```
$ file main
main: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped
```

**Comment by jhheider** [comment]
I wonder if that's related to this: https://github.com/denoland/deno/issues/22690

Does it work with older version? if you do `pkgx +deno~1.40 deno compile...` does it help?

**Comment by jhheider** [comment]
note that you also have two --output statements to the same destination. i don't know if that significant with the placement order of flags.

**Comment by tsirysndr** [comment]
it appears the issue is not related to Deno itself but rather to the Deno installation from pkgx. It works pretty good in ubuntu:latest and deno:latest

**Comment by jhheider** [comment]
And those are the up-to-date version as well? I can look into it, but based on that issue versions was my first guess.

**Comment by tsirysndr** [comment]
Yes, I can confirm that I am using the latest version of deno (1.45.3)

**Comment by jhheider** [comment]
ok, interesting one. the problem is this:
```yaml
runtime:
  env:
    DENORT_BIN: '{{prefix}}/bin/denort'
```

so, that line is there because their recently-added linux/aarch64 support targeted the glibc for ubuntu22.04 and we support much further back than that. if i comment that out, i can cross-build the apple targets (with unzip) as it grabs their downloadable runtime.

so, I think for now, I'm going to remove this, and explicitly set it in the test stanza. we'll need to update the couple of builds that rely on it (`pkgx`) being one of them, but that's not a big deal. when i merge this, it should Just Work™ for you without needing to wait on the build, since we're just changing the configuration. should be ready shortly.
